# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Trinkewitz-Ausstellung'
description:      '„Die unerträgliche Leichtigkeit des Haiku“ – Der Künstler Karel Trinkewitz'
url:              ''
baseurl:          ''
#url:              'https://jsektkuehler.github.io'
#baseurl:          '/trinkewitz_digital'
copyright:        'Copyright Leibniz-Institut für Geschichte und Kultur des östlichen Europa (GWZO). [Online-Ausstellung Trinkewitz, Januar 2017]'
logo:             'img/logo-platzhalter.png'
default_thumb:    'img/logo-platzhalter.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude: ["drafts","todo.txt", "Gemfile*", "*.gemspec", "Rakefile", "vendor", "spec", "README.md", "LICENSE.txt", "Docker*", "parallax_index.html", "from_teaser_layouts_index.html", "index_not_displaying.html"]
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/


collections:
  pages:
    output: true
  #exhibits:
  #  output: false
  trinkewitz: # name of collection
    output: true # makes sure pages are output as html files
    layout: trinkewitz_item # trinkewitz_item # the layout for the pages to use
    metadata:
      source: trinkewitz.csv # path to the metadata file within `_data`
    images:
      source: raw_images/trinkewitz # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      trinkewitz:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - artist
          - label
          - _date
          - source
          - pid
          - overviewPage_title

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'START'
    link: '/start'
  - label: 'TAFELN'
    link: '/tafeln/'
  - label: 'LEBEN-KUNST'
    link: '/leben/'
  - label: 'IMPRESSUM'
    link: '/impressum/'
  - label: 'Suche'
    link: '/search/'
  #- label: 'Trinkewitz'
  #  link: '/trinkewitz/'
  #- label: 'Übersicht'
  #  link: '/uebersicht/'
  #- label: 'Nachnutzung'
  #  link: '/reuse/'
    #sub:
      #- label: 'Vertiefung Tafel 2: Meine kurze Autobiographie'
      #  link: '/vertiefung-tafel-2-meine-kurze-autobiographie'
      #- label: 'Vertiefung Tafel 2: Kurzer Lebenslauf'
      #  link: '/vertiefung-tafel-2-tabellarischer-lebenslauf'
      #- label: 'Vertiefung Tafel 3: Überlegungen zum Haiku'
      #  link: '/vertiefung-tafel-3-ueberlegungen-zum-haiku'
      #- label: 'Vertiefung Tafel 3: Poesie des Augenblicks und der Ewigkeit'
      #  link: '/vertiefung-tafel-3-poesie-des-augenblicks-und-der-ewigkeit'
      #- label: 'Vertiefung Tafel 3: Die unerträgliche Leichtigkeit des Haiku'
      #  link: '/vertiefung-tafel-3-die-unertraegliche-leichtigkeit-des-haiku'
      #- label: 'Vertiefung Tafel 3: Haijin Trinkewitz'
      #  link: '/vertiefung-tafel-3-haijin-trinkewitz'
      #- label: 'Vertiefung Tafel 4 und 7: Reise nach Saarbrücken'
      #  link: 'vertiefung-tafel-4-und-7-reise-nach-saarbruecken'
# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'Impressum'
      link: '/impressum'
    - label: 'Datenschutz'
      link: 'datenschutz'
  #logos:
  #  - img: 'img/logo-platzhalter.png'
  #  - img: 'img/logo-platzhalter.png'

# FIN
